# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pmmx' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pmmx
  pod 'Alamofire'
  #pod 'Koloda'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Charts'
  pod 'FSCalendar'
  pod 'KDCircularProgress'
  pod 'CircleMenu'
  #pod 'Persei'

  target 'pmmxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pmmxUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
